autolabeler:
  - label: 'new-release'
    branch:
      - '/develop/'
      - '/develop-.+/'
  - label: 'data-integration'
    branch:
      - '/data-.+/'
  - label: 'bug'
    branch:
      - '/bug-.+/'
      - '/bugfix-.+/'
      - '/fix-.+/'
  - label: 'feature'
    branch:
      - '/feature-.+/'
      - '/feat-.+/'
  - label: 'skip-release-note'
    branch:
      - '/update_README\.md/'
      - '/norn-.+/'
      - '/skiprn-.+/'
template: '# Labeler'