name: PR Milestone Auto Edit

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - edited

jobs:
  pr-edit:
    uses: geoadmin/.github/.github/workflows/pr-auto-milestone.yml@master
