name: Milestone Release Reusable Workflow

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump Milestone Tag
      id: tagging
      uses: geoadmin/action-milestone-tag@v0.1.0-beta.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: '${MILESTONE}_rc${TAG_NUMBER}'
        milestone_pattern: '\d{4}-\d{2}-\d{2}'

    # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: Create Release with Release Notes
      uses: release-drafter/release-drafter@v5
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        config-name: release-drafter-config.yml
        disable-autolabeler: true
        publish: true
        tag: ${{ steps.tagging.outputs.new_tag }}
        version: ${{ steps.tagging.outputs.new_tag }}
        name: ${{ steps.tagging.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}