name: Add Pull Request to Milestone

on:
  workflow_call:
  # pull_request:
  #   types:
  #     - opened

jobs:
  add-to-milestone:
    name: Add Pull Request to Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: iyu/actions-milestone@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/pr-2-milestone-config.yml